### PR TITLE
jitter to position

### PR DESCRIPTION
**Pull request by futuretech6**

### CODE REVIEW

**Comment by AsterNighT** [comment]
Is it tested and verified?

**Comment by futuretech6** [comment]
> Is it tested and verified?

Sure, I test it on the "config.json not found, running as github actions or so" mode locally, since the modification part is in function `run`, so it will work for both mode I think.

**Comment by futuretech6** [comment]
> Is it tested and verified?

But I haven't test it on github actions, maybe I can test it tomorrow

**Comment by AsterNighT** [comment]
> > Is it tested and verified?
> 
> But I haven't test it on github actions, maybe I can test it tomorrow

And make sure this jitter won't make you out of Hangzhou lol

**Comment by futuretech6** [comment]
test done [here](https://github.com/FUTURETECH6/sisyphus/runs/6778216476?check_suite_focus=true), and to prevent "out of range" error I update the max jitter length to about 200 meters in 2b1ea72c0970c1edc96d1ea1414a2917047d4077

**Comment by futuretech6** [comment]
and maybe you can help me to deal with `Math.random()` warnings proposed by sonatype-lift bot

**Comment by AsterNighT** [comment]
> and maybe you can help me to deal with `Math.random()` warnings proposed by sonatype-lift bot

Just ignore it. You are not really writing a cryptographic program

**Pull request merged**
